### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dirshell** [PlatyPew/PwnBox2#1]
hi，friends，when i run build.sh in folder /root/PwnBox2，the erros accurs，i try servel methods to connect，include use shadowsocksR  and have never seen it work. ，could you help me to resolve this error？thank you very muck！

resolving dependencies...
looking for conflicting packages...

Packages (1) go-2:1.13.3-1

Total Download Size:   122.42 MiB
Total Installed Size:  478.81 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'go-2:1.13.3-1-x86_64.pkg.tar.xz' from mirror.aktkn.sg : Empty reply from server
error: failed retrieving file 'go-2:1.13.3-1-x86_64.pkg.tar.xz' from mirror.aktkn.sg : Empty reply from server
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> go
==> ERROR: Could not resolve all dependencies.
The command '/bin/sh -c git clone https://aur.archlinux.org/yay.git &&     cd yay &&     makepkg -si --noconfirm' returned a non-zero code: 8

**Comment by PlatyPew** [comment]
You can try changing the mirror using reflector in the Dockerfile. As of now, it's set to connect to Singapore's mirror.
