### ISSUE TITLE
tmpfs error

### ISSUE THREAD

**Issue by niqdev** [PlatyPew/PwnBox2#12]
Hi, is there an easy way to run the image or edit the script to avoid mounting the volumes?

I built something similar with [hckops/hckctl](https://github.com/hckops/hckctl) but more generic and I've added your image to the [catalog](https://github.com/hckops/megalopolis/blob/main/box/preview/pwnpad.yml) but it's not working.

I'm basically supporting out of the box most of the flags [here](https://github.com/pwnpad/pwnpad/blob/master/p2#L170) but the image is looking for a default path `/run` that doesn't exists

In order to debug the issue I run
```bash
docker run -it --rm platypew/pwnpad bash
cat: /usr/share/zoneinfo/: Is a directory
Created symlink /etc/systemd/system/systemd-firstboot.service → /dev/null.
Created symlink /etc/systemd/system/systemd-udevd.service → /dev/null.
Created symlink /etc/systemd/system/multi-user.target.wants/docker-entrypoint.service → /etc/systemd/system/docker-entrypoint.service.
/docker-entrypoint.sh: starting /lib/systemd/systemd --show-status=false --unit=docker-entrypoint.target
Failed to mount tmpfs (type tmpfs) on /run (MS_NOSUID|MS_NODEV|MS_STRICTATIME "mode=0755,size=20%,nr_inodes=800k"): Operation not permitted
[!!!!!!] Failed to mount API filesystems.
Exiting PID 1...
```

If you are interested, I can help out to fix the issue or build a slightly different image to support my use case. If I get it working I should be able to run the image and replace most of the command in `p2` with something like this
```bash
hckctl box pwnpad
```

**Comment by PlatyPew** [comment]
Currently, pwnpad supports systemd, which requires the /run tmpfs.
If you would like to avoid mounting said volumes, you would have to remove the systemd feature (which does not really break anything, it's more of a convenience feature)

You may build a slightly different image that removes these lines which are responsible for starting systemd
https://github.com/pwnpad/pwnpad/blob/eb446d9cb95c73e34bfb5d9aeb74c6ca025c84c5/config/docker-entrypoint.sh#L9-L70

**Comment by PlatyPew** [comment]
I've added a new bare image and can be pulled from `platypew/pwnpad:bare`
This one only includes the tools and removes systemd so mounting is not required.
Hope it solves the issue!

**Comment by niqdev** [comment]
Awesome, thanks a lot. Let me test it and I'll give you a feedback!

**Comment by niqdev** [comment]
Yup that works as expected! Thanks

Would you mind give it a spin with my tool, follow the [installation](https://github.com/hckops/hckctl?tab=readme-ov-file#setup) and then run
```
hckctl box pwnpad
```

This should be similar to your `p2` command but more generic and I'm curious to know what do you think and if you have any feedback!

**Comment by PlatyPew** [comment]
Looks great! Now that I think of it, I should leave Neovim inside the bare image.
